import Header from "@/components/header";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { getBrands, getCategories } from "@/lib/queries";
import CartProvider from "@/components/cartProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [categories, cErr] = await getCategories();
  const [brands, bErr] = await getBrands();
  return (
    <html lang="en">
      <body
        className={cn("flex flex-col h-dynamic bg-gray-100", inter.className)}
      >
        <CartProvider>
          <Header categories={categories} brands={brands} />
          {children}
        </CartProvider>
        <Toaster />
      </body>
    </html>
  );
}
