import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { getBrands, getCategories } from "@/lib/queries";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [categories, cErr] = await getCategories();
  const [brands, bErr] = await getBrands();
  return (
    <html lang="en">
      <body className={cn("flex flex-col gap-4", inter.className)}>
        <Header categories={categories} brands={brands} />
        {children}
      </body>
    </html>
  );
}
